#ifndef I386_ASM_H_
#define I386_ASM_H_

#define THREAD_MD_PREVIOUS_TASK 0
#define THREAD_MD_ESP0 4
#define THREAD_MD_SS0 8
#define THREAD_MD_ESP1 12
#define THREAD_MD_SS1 16
#define THREAD_MD_ESP2 20
#define THREAD_MD_SS2 24
#define THREAD_MD_CR3 28
#define THREAD_MD_EIP 32
#define THREAD_MD_EFLAGS 36
#define THREAD_MD_EAX 40
#define THREAD_MD_ECX 44
#define THREAD_MD_EDX 48
#define THREAD_MD_EBX 52
#define THREAD_MD_ESP 56
#define THREAD_MD_EBP 60
#define THREAD_MD_ESI 64
#define THREAD_MD_EDI 68
#define THREAD_MD_ES 72
#define THREAD_MD_CS 76
#define THREAD_MD_SS 80
#define THREAD_MD_DS 84
#define THREAD_MD_FS 88
#define THREAD_MD_GS 92
#define THREAD_MD_LDT_SEGMENT_SELECTOR 96
#define THREAD_MD_T 100
#define THREAD_MD_IO_MAP_BASE_ADDRESS 104

#define GLOBAL_32BIT_CODE 0x08
#define GLOBAL_32BIT_DATA 0x10
#define GLOBAL_32BIT_TSS 0x18
#endif
