#ifndef KERN_SYSCALL_H
#define KERN_SYSCALL_H

enum {
	SYSCALL_PUTCHAR,
	SYSCALL_GETCHAR,
	SYSCALL_GETATTR,
	SYSCALL_OPENDIR,
	SYSCALL_READDIR,
	SYSCALL_SEEKDIR,
	SYSCALL_TELLDIR,
	SYSCALL_CLOSEDIR,
	SYSCALL_OPEN,
	SYSCALL_READ,
	SYSCALL_LSEEK,
	SYSCALL_CLOSE,
	SYSCALL_MAX
};

void *syscall_entries[SYSCALL_MAX];
#endif
